version: '2'

services:
  eureka:
    image: goopnigoop/eureka:latest
    ports:
      - "8761:8761"
  zuul:
    image: goopnigoop/zuul:latest
    ports:
      - "8766:8766"
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka/'
      UREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
  config:
    image: goopnigoop/config:latest
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka/'
      UREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    depends_on:
      - config
  pc:
      image: goopnigoop/pc:latest
      ports:
        - '8081:8080'
      depends_on:
        - eureka
        - mongo
        - config
      environment:
        SPRING_DATA_MONGODB_HOST: mongo
        UREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka/'
  po:
      image: goopnigoop/po:latest
      ports:
        - '8082:8080'
      links:
        - pc
      depends_on:
        - eureka
        - mongo
        - pc
        - config
      environment:
        SPRING_DATA_MONGODB_HOST: mongo
        EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
        pcurl: 'pc:8080'
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka/'
networks:
    default:
        driver: bridge
