version: '2'

services:
  eureka:
    image: goopnigoop/eureka:latest
    ports:
      - "8761:8761"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  pc:
      image: goopnigoop/pc:latest
      ports:
        - '8081:8080'
      depends_on:
        - eureka
        - mongo
      environment:
        SPRING_DATA_MONGODB_HOST: mongo
        UREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka/'
  po:
      image: goopnigoop/po:latest
      ports:
        - '8082:8080'
      links:
        - pc
      depends_on:
        - eureka
        - mongo
        - pc
      environment:
        SPRING_DATA_MONGODB_HOST: mongo
        EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
        pcurl: 'pc:8080'
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka/'
networks:
    default:
        driver: bridge
